webhookUrl: YOUR_WEBHOOK_URL
join-message: "&e%player% joined the game"
leave-message: "&e%player% left the game"
world-change-message: "Welcome %player% to %world_name%"
join-message-webhook: "%player% joined the game"
leave-message-webhook: "%player% left the game"
world-change-webhook: "%player% go to %world_name%"
on-start-webhook: "YOUR_SERVER_NAME is Started"
on-stop-webhook: "YOUR_SERVER_NAME is Stopped"