name: M2SMP
version: '${version}'
main: hewkawar.plugin.M2SMP
api-version: '1.20'
commands:
  status:
    description: Open Player's Status
  login:
    description: Login

softdepend: [PlaceholderAPI]